using System.Collections.Concurrent;
using System.IO.Pipes;
using SteamInputAddonforClaw.Contracts.Frontend;

namespace SteamInputAddonforClaw.FrontendTransport;

public sealed class NamedPipeAddonFrontendServer : IAsyncDisposable
{
    private readonly string _pipeName; private readonly IAddonFrontendControl _inner; private readonly CancellationTokenSource _lifetime = new(); private Task? _acceptLoop; private int _started;
    public NamedPipeAddonFrontendServer(string pipeName, IAddonFrontendControl inner) { _pipeName = pipeName; _inner = inner; }
    public Task StartAsync() { if (Interlocked.Exchange(ref _started, 1) != 0) throw new InvalidOperationException("Server already started."); _acceptLoop = AcceptLoopAsync(); return Task.CompletedTask; }
    private async Task AcceptLoopAsync()
    { while (!_lifetime.IsCancellationRequested) { try { await using var pipe = new NamedPipeServerStream(_pipeName, PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous | PipeOptions.CurrentUserOnly); await pipe.WaitForConnectionAsync(_lifetime.Token).ConfigureAwait(false); await ServeAsync(pipe, _lifetime.Token).ConfigureAwait(false); } catch (OperationCanceledException) when (_lifetime.IsCancellationRequested) { } catch { } } }
    private async Task ServeAsync(Stream pipe, CancellationToken token)
    { using var connection = CancellationTokenSource.CreateLinkedTokenSource(token); using var gate = new SemaphoreSlim(1, 1); var requests = new ConcurrentDictionary<long, CancellationTokenSource>(); var operationGate = new SemaphoreSlim(1, 1); int invalidationPending = 0;
        async Task Send(FrontendWireEnvelope e) => await FrontendWireCodec.WriteAsync(pipe, e, gate, connection.Token).ConfigureAwait(false);
        async Task Notify() { try { await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.Notification, Notification: FrontendNotificationKind.StateInvalidated)); } catch { } finally { Volatile.Write(ref invalidationPending, 0); } }
        void Invalidated(object? _, EventArgs __) { if (Interlocked.Exchange(ref invalidationPending, 1) == 0) _ = Notify(); }
        try { var hello = await FrontendWireCodec.ReadAsync(pipe, connection.Token).ConfigureAwait(false); if (hello.Kind != FrontendWireMessageKind.Handshake || hello.ProtocolVersion != FrontendTransportProtocol.CurrentVersion) { await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.ProtocolError, Error: new(FrontendRemoteErrorCode.ProtocolMismatch, "Protocol version mismatch."))).ConfigureAwait(false); return; } await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.HandshakeAccepted)).ConfigureAwait(false); _inner.StateInvalidated += Invalidated;
            while (!connection.IsCancellationRequested) { var message = await FrontendWireCodec.ReadAsync(pipe, connection.Token).ConfigureAwait(false); if (message.Kind == FrontendWireMessageKind.CancelRequest && message.RequestId is > 0 and var cancelId) { if (requests.TryGetValue(cancelId, out var cancellation)) cancellation.Cancel(); continue; } if (message.Kind != FrontendWireMessageKind.Request || message.RequestId is not > 0 || message.Method is null || !requests.TryAdd(message.RequestId.Value, CancellationTokenSource.CreateLinkedTokenSource(connection.Token))) throw new FrontendProtocolException("Invalid request."); var id = message.RequestId.Value; var requestCts = requests[id]; _ = Task.Run(async () => { try { await operationGate.WaitAsync(requestCts.Token).ConfigureAwait(false); try { var payload = await InvokeAsync(message.Method.Value, message.Payload, requestCts.Token).ConfigureAwait(false); await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.Response, id, message.Method, Payload: payload)).ConfigureAwait(false); } finally { operationGate.Release(); } } catch (OperationCanceledException) { await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.Response, id, Error: new(FrontendRemoteErrorCode.Cancelled, "Operation cancelled."))).ConfigureAwait(false); } catch (Exception e) { await Send(new(FrontendTransportProtocol.CurrentVersion, FrontendWireMessageKind.Response, id, Error: new(FrontendRemoteErrorCode.OperationFailed, e.Message))).ConfigureAwait(false); } finally { requests.TryRemove(id, out _); requestCts.Dispose(); } }); } }
        finally { _inner.StateInvalidated -= Invalidated; connection.Cancel(); foreach (var item in requests.Values) item.Cancel(); operationGate.Dispose(); }
    }
    private async Task<System.Text.Json.JsonElement> InvokeAsync(FrontendRpcMethod m, System.Text.Json.JsonElement? p, CancellationToken t) => m switch
    { FrontendRpcMethod.GetBootstrap => FrontendWireCodec.Payload(await _inner.GetBootstrapAsync(t).ConfigureAwait(false)), FrontendRpcMethod.CaptureStatus => FrontendWireCodec.Payload(await _inner.CaptureStatusAsync(t).ConfigureAwait(false)), FrontendRpcMethod.SetLaunchAtWindowsStartup => FrontendWireCodec.Payload(await _inner.SetLaunchAtWindowsStartupAsync(FrontendWireCodec.Decode<SetLaunchAtWindowsStartupRequest>(p).Enabled, t).ConfigureAwait(false)), FrontendRpcMethod.SetRouteInSteamBigPicture => FrontendWireCodec.Payload(await _inner.SetRouteInSteamBigPictureAsync(FrontendWireCodec.Decode<SetRouteInSteamBigPictureRequest>(p).Enabled, t).ConfigureAwait(false)), FrontendRpcMethod.SetLogLevel => FrontendWireCodec.Payload(await _inner.SetLogLevelAsync(FrontendWireCodec.Decode<SetLogLevelRequest>(p).Level, t).ConfigureAwait(false)), FrontendRpcMethod.SuppressDeveloperMenuWarning => FrontendWireCodec.Payload(await _inner.SuppressDeveloperMenuWarningAsync(t).ConfigureAwait(false)), FrontendRpcMethod.SetDeveloperTestMode => FrontendWireCodec.Payload(await _inner.SetDeveloperTestModeAsync(FrontendWireCodec.Decode<SetDeveloperTestModeRequest>(p).Enabled, t).ConfigureAwait(false)), FrontendRpcMethod.RunPrerequisiteSetup => FrontendWireCodec.Payload(await _inner.RunPrerequisiteSetupAsync(t).ConfigureAwait(false)), FrontendRpcMethod.GenerateEnvironmentReport => FrontendWireCodec.Payload(await _inner.GenerateEnvironmentReportAsync(t).ConfigureAwait(false)), _ => throw new FrontendProtocolException("Unsupported method.") };
    public async ValueTask DisposeAsync() { _lifetime.Cancel(); if (_acceptLoop is not null) try { await _acceptLoop.ConfigureAwait(false); } catch { } _lifetime.Dispose(); }
}
