/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/Alia5/VIIPER/lib/viiper */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bus.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

#line 1 "cgo-generated-wrapper"

#line 3 "device.go"

#include <stdbool.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "dualsense.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t DSDeviceHandle;

#define DS_BUTTON_SQUARE    0x00000010u
#define DS_BUTTON_CROSS     0x00000020u
#define DS_BUTTON_CIRCLE    0x00000040u
#define DS_BUTTON_TRIANGLE  0x00000080u
#define DS_BUTTON_L1        0x00000100u
#define DS_BUTTON_R1        0x00000200u
#define DS_BUTTON_L2        0x00000400u
#define DS_BUTTON_R2        0x00000800u
#define DS_BUTTON_CREATE    0x00001000u
#define DS_BUTTON_OPTIONS   0x00002000u
#define DS_BUTTON_L3        0x00004000u
#define DS_BUTTON_R3        0x00008000u
#define DS_BUTTON_PS        0x00010000u
#define DS_BUTTON_TOUCHPAD  0x00020000u
#define DS_BUTTON_MIC_MUTE  0x00040000u
#define DS_BUTTON_RFN       0x00200000u
#define DS_BUTTON_LFN       0x00100000u
#define DS_BUTTON_R4        0x00800000u
#define DS_BUTTON_L4        0x00400000u

#define DS_DPAD_UP     0x01u
#define DS_DPAD_DOWN   0x02u
#define DS_DPAD_LEFT   0x04u
#define DS_DPAD_RIGHT  0x08u

#define DS_SHELL_COLOR_WHITE                    "00"
#define DS_SHELL_COLOR_BLACK                    "01"
#define DS_SHELL_COLOR_COSMIC_RED               "02"
#define DS_SHELL_COLOR_NOVA_PINK                "03"
#define DS_SHELL_COLOR_GALACTIC_PURPLE          "04"
#define DS_SHELL_COLOR_STARLIGHT_BLUE           "05"
#define DS_SHELL_COLOR_GREY_CAMOUFLAGE          "06"
#define DS_SHELL_COLOR_VOLCANIC_RED             "07"
#define DS_SHELL_COLOR_STERLING_SILVER          "08"
#define DS_SHELL_COLOR_COBALT_BLUE              "09"
#define DS_SHELL_COLOR_CHROMA_TEAL              "10"
#define DS_SHELL_COLOR_CHROMA_INDIGO            "11"
#define DS_SHELL_COLOR_CHROMA_PEARL             "12"
#define DS_SHELL_COLOR_ANNIVERSARY_30TH         "30"
#define DS_SHELL_COLOR_GOD_OF_WAR_RAGNAROK      "Z1"
#define DS_SHELL_COLOR_SPIDER_MAN_2             "Z2"
#define DS_SHELL_COLOR_ASTRO_BOT                "Z3"
#define DS_SHELL_COLOR_FORTNITE                 "Z4"
#define DS_SHELL_COLOR_MONSTER_HUNTER_WILDS     "Z5"
#define DS_SHELL_COLOR_THE_LAST_OF_US           "Z6"
#define DS_SHELL_COLOR_GHOST_OF_YOTEI           "Z7"
#define DS_SHELL_COLOR_ICON_BLUE_LIMITED_EDITION "ZB"
#define DS_SHELL_COLOR_ASTRO_BOT_JOYFUL_EDITION "ZC"
#define DS_SHELL_COLOR_GENSHIN_IMPACT           "ZE"

typedef struct {
	int8_t   LX;
	int8_t   LY;
	int8_t   RX;
	int8_t   RY;
	uint32_t Buttons;
	uint8_t  DPad;
	uint8_t  L2;
	uint8_t  R2;
	uint16_t Touch1X;
	uint16_t Touch1Y;
	uint8_t  Touch1Active;
	uint16_t Touch2X;
	uint16_t Touch2Y;
	uint8_t  Touch2Active;
	int16_t  GyroX;
	int16_t  GyroY;
	int16_t  GyroZ;
	int16_t  AccelX;
	int16_t  AccelY;
	int16_t  AccelZ;
} DSDeviceState;

typedef struct {
	const char* SerialNumber;       // NULL = use default
	const char* MACAddress;         // NULL = use default
	const char* Board;              // NULL = use default
	uint8_t     BatteryStatus;      // 0 = use default
	double      TemperatureCelsius; // 0 = use default
	double      BatteryVoltage;     // 0 = use default
	const char* ShellColor;     // NULL = use default (2-char code, e.g. "00", "Z1")
} DSMetaState;

typedef void (*DSOutputCallback)(DSDeviceHandle handle, uint8_t rumbleSmall, uint8_t rumbleLarge, uint8_t ledRed, uint8_t ledGreen, uint8_t ledBlue, uint8_t playerLeds);

static void viiper_call_ds_output(DSOutputCallback fn, DSDeviceHandle handle, uint8_t rumbleSmall, uint8_t rumbleLarge, uint8_t ledRed, uint8_t ledGreen, uint8_t ledBlue, uint8_t playerLeds) {
	fn(handle, rumbleSmall, rumbleLarge, ledRed, ledGreen, ledBlue, playerLeds);
}


#line 1 "cgo-generated-wrapper"

#line 3 "dualshock4.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t DS4DeviceHandle;

#define DS4_BUTTON_SQUARE    0x0010u
#define DS4_BUTTON_CROSS     0x0020u
#define DS4_BUTTON_CIRCLE    0x0040u
#define DS4_BUTTON_TRIANGLE  0x0080u
#define DS4_BUTTON_L1        0x0100u
#define DS4_BUTTON_R1        0x0200u
#define DS4_BUTTON_L2        0x0400u
#define DS4_BUTTON_R2        0x0800u
#define DS4_BUTTON_SHARE     0x1000u
#define DS4_BUTTON_OPTIONS   0x2000u
#define DS4_BUTTON_L3        0x4000u
#define DS4_BUTTON_R3        0x8000u
#define DS4_BUTTON_PS        0x0001u
#define DS4_BUTTON_TOUCHPAD  0x0002u

#define DS4_DPAD_UP        0x00u
#define DS4_DPAD_UP_RIGHT  0x01u
#define DS4_DPAD_RIGHT     0x02u
#define DS4_DPAD_DOWN_RIGHT 0x03u
#define DS4_DPAD_DOWN      0x04u
#define DS4_DPAD_DOWN_LEFT 0x05u
#define DS4_DPAD_LEFT      0x06u
#define DS4_DPAD_UP_LEFT   0x07u
#define DS4_DPAD_NEUTRAL   0x08u

typedef struct {
	int8_t   LX;
	int8_t   LY;
	int8_t   RX;
	int8_t   RY;
	uint16_t Buttons;
	uint8_t  DPad;
	uint8_t  L2;
	uint8_t  R2;
	uint16_t Touch1X;
	uint16_t Touch1Y;
	uint8_t  Touch1Active;
	uint16_t Touch2X;
	uint16_t Touch2Y;
	uint8_t  Touch2Active;
	int16_t  GyroX;
	int16_t  GyroY;
	int16_t  GyroZ;
	int16_t  AccelX;
	int16_t  AccelY;
	int16_t  AccelZ;
} DS4DeviceState;

typedef struct {
	const char* SerialNumber;       // NULL = use default
	const char* Board;              // NULL = use default
	uint8_t     BatteryStatus;      // 0 = use default
	double      TemperatureCelsius; // 0 = use default
	double      BatteryVoltage;     // 0 = use default
} DS4MetaState;

typedef void (*DS4OutputCallback)(DS4DeviceHandle handle, uint8_t rumbleSmall, uint8_t rumbleLarge, uint8_t ledRed, uint8_t ledGreen, uint8_t ledBlue, uint8_t flashOn, uint8_t flashOff);

static void viiper_call_ds4_output(DS4OutputCallback fn, DS4DeviceHandle handle, uint8_t rumbleSmall, uint8_t rumbleLarge, uint8_t ledRed, uint8_t ledGreen, uint8_t ledBlue, uint8_t flashOn, uint8_t flashOff) {
	fn(handle, rumbleSmall, rumbleLarge, ledRed, ledGreen, ledBlue, flashOn, flashOff);
}


#line 1 "cgo-generated-wrapper"

#line 3 "keyboard.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t KeyboardDeviceHandle;

#define KB_MOD_LEFT_CTRL   0x01u
#define KB_MOD_LEFT_SHIFT  0x02u
#define KB_MOD_LEFT_ALT    0x04u
#define KB_MOD_LEFT_GUI    0x08u
#define KB_MOD_RIGHT_CTRL  0x10u
#define KB_MOD_RIGHT_SHIFT 0x20u
#define KB_MOD_RIGHT_ALT   0x40u
#define KB_MOD_RIGHT_GUI   0x80u

#define KB_LED_NUM_LOCK    0x01u
#define KB_LED_CAPS_LOCK   0x02u
#define KB_LED_SCROLL_LOCK 0x04u
#define KB_LED_COMPOSE     0x08u
#define KB_LED_KANA        0x10u

#define KB_KEY_A 0x04u
#define KB_KEY_B 0x05u
#define KB_KEY_C 0x06u
#define KB_KEY_D 0x07u
#define KB_KEY_E 0x08u
#define KB_KEY_F 0x09u
#define KB_KEY_G 0x0Au
#define KB_KEY_H 0x0Bu
#define KB_KEY_I 0x0Cu
#define KB_KEY_J 0x0Du
#define KB_KEY_K 0x0Eu
#define KB_KEY_L 0x0Fu
#define KB_KEY_M 0x10u
#define KB_KEY_N 0x11u
#define KB_KEY_O 0x12u
#define KB_KEY_P 0x13u
#define KB_KEY_Q 0x14u
#define KB_KEY_R 0x15u
#define KB_KEY_S 0x16u
#define KB_KEY_T 0x17u
#define KB_KEY_U 0x18u
#define KB_KEY_V 0x19u
#define KB_KEY_W 0x1Au
#define KB_KEY_X 0x1Bu
#define KB_KEY_Y 0x1Cu
#define KB_KEY_Z 0x1Du
#define KB_KEY_1 0x1Eu
#define KB_KEY_2 0x1Fu
#define KB_KEY_3 0x20u
#define KB_KEY_4 0x21u
#define KB_KEY_5 0x22u
#define KB_KEY_6 0x23u
#define KB_KEY_7 0x24u
#define KB_KEY_8 0x25u
#define KB_KEY_9 0x26u
#define KB_KEY_0 0x27u
#define KB_KEY_ENTER      0x28u
#define KB_KEY_ESCAPE     0x29u
#define KB_KEY_BACKSPACE  0x2Au
#define KB_KEY_TAB        0x2Bu
#define KB_KEY_SPACE      0x2Cu
#define KB_KEY_MINUS      0x2Du
#define KB_KEY_EQUAL      0x2Eu
#define KB_KEY_LEFT_BRACE  0x2Fu
#define KB_KEY_RIGHT_BRACE 0x30u
#define KB_KEY_BACKSLASH  0x31u
#define KB_KEY_SEMICOLON  0x33u
#define KB_KEY_APOSTROPHE 0x34u
#define KB_KEY_GRAVE      0x35u
#define KB_KEY_COMMA      0x36u
#define KB_KEY_PERIOD     0x37u
#define KB_KEY_SLASH      0x38u
#define KB_KEY_CAPS_LOCK  0x39u
#define KB_KEY_F1  0x3Au
#define KB_KEY_F2  0x3Bu
#define KB_KEY_F3  0x3Cu
#define KB_KEY_F4  0x3Du
#define KB_KEY_F5  0x3Eu
#define KB_KEY_F6  0x3Fu
#define KB_KEY_F7  0x40u
#define KB_KEY_F8  0x41u
#define KB_KEY_F9  0x42u
#define KB_KEY_F10 0x43u
#define KB_KEY_F11 0x44u
#define KB_KEY_F12 0x45u
#define KB_KEY_PRINT_SCREEN 0x46u
#define KB_KEY_SCROLL_LOCK  0x47u
#define KB_KEY_PAUSE        0x48u
#define KB_KEY_INSERT       0x49u
#define KB_KEY_HOME         0x4Au
#define KB_KEY_PAGE_UP      0x4Bu
#define KB_KEY_DELETE       0x4Cu
#define KB_KEY_END          0x4Du
#define KB_KEY_PAGE_DOWN    0x4Eu
#define KB_KEY_RIGHT        0x4Fu
#define KB_KEY_LEFT         0x50u
#define KB_KEY_DOWN         0x51u
#define KB_KEY_UP           0x52u
#define KB_KEY_NUM_LOCK     0x53u
#define KB_KEY_KP_SLASH     0x54u
#define KB_KEY_KP_ASTERISK  0x55u
#define KB_KEY_KP_MINUS     0x56u
#define KB_KEY_KP_PLUS      0x57u
#define KB_KEY_KP_ENTER     0x58u
#define KB_KEY_KP_1 0x59u
#define KB_KEY_KP_2 0x5Au
#define KB_KEY_KP_3 0x5Bu
#define KB_KEY_KP_4 0x5Cu
#define KB_KEY_KP_5 0x5Du
#define KB_KEY_KP_6 0x5Eu
#define KB_KEY_KP_7 0x5Fu
#define KB_KEY_KP_8 0x60u
#define KB_KEY_KP_9 0x61u
#define KB_KEY_KP_0 0x62u
#define KB_KEY_KP_DOT 0x63u
#define KB_KEY_MUTE        0x7Fu
#define KB_KEY_VOLUME_UP   0x80u
#define KB_KEY_VOLUME_DOWN 0x81u

typedef struct {
	uint8_t Modifiers;
	uint8_t KeyBitmap[32];
} KeyboardDeviceState;

typedef void (*KeyboardLEDCallback)(KeyboardDeviceHandle handle, uint8_t leds);

static void viiper_call_kb_led(KeyboardLEDCallback fn, KeyboardDeviceHandle handle, uint8_t leds) {
	fn(handle, leds);
}


#line 1 "cgo-generated-wrapper"

#line 3 "mouse.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t MouseDeviceHandle;

#define MOUSE_BTN_LEFT    0x01u
#define MOUSE_BTN_RIGHT   0x02u
#define MOUSE_BTN_MIDDLE  0x04u
#define MOUSE_BTN_BACK    0x08u
#define MOUSE_BTN_FORWARD 0x10u

typedef struct {
	uint8_t Buttons;
	int16_t DX;
	int16_t DY;
	int16_t Wheel;
	int16_t Pan;
} MouseDeviceState;


#line 1 "cgo-generated-wrapper"

#line 3 "ns2pro.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t NS2ProDeviceHandle;

#define NS2PRO_BUTTON_B            0x00000001u
#define NS2PRO_BUTTON_A            0x00000002u
#define NS2PRO_BUTTON_Y            0x00000004u
#define NS2PRO_BUTTON_X            0x00000008u
#define NS2PRO_BUTTON_R            0x00000010u
#define NS2PRO_BUTTON_ZR           0x00000020u
#define NS2PRO_BUTTON_PLUS         0x00000040u
#define NS2PRO_BUTTON_RIGHT_STICK  0x00000080u
#define NS2PRO_BUTTON_DOWN         0x00000100u
#define NS2PRO_BUTTON_RIGHT        0x00000200u
#define NS2PRO_BUTTON_LEFT         0x00000400u
#define NS2PRO_BUTTON_UP           0x00000800u
#define NS2PRO_BUTTON_L            0x00001000u
#define NS2PRO_BUTTON_ZL           0x00002000u
#define NS2PRO_BUTTON_MINUS        0x00004000u
#define NS2PRO_BUTTON_LEFT_STICK   0x00008000u
#define NS2PRO_BUTTON_HOME         0x00010000u
#define NS2PRO_BUTTON_CAPTURE      0x00020000u
#define NS2PRO_BUTTON_GR           0x00040000u
#define NS2PRO_BUTTON_GL           0x00080000u
#define NS2PRO_BUTTON_C            0x00100000u
#define NS2PRO_BUTTON_HEADSET      0x00200000u

#define NS2PRO_STICK_MIN    0x0000u
#define NS2PRO_STICK_CENTER 0x0800u
#define NS2PRO_STICK_MAX    0x0FFFu

#define NS2PRO_FEATURE_BUTTONS 0x01u
#define NS2PRO_FEATURE_STICKS  0x02u
#define NS2PRO_FEATURE_IMU     0x04u
#define NS2PRO_FEATURE_MOUSE   0x10u
#define NS2PRO_FEATURE_RUMBLE  0x20u

typedef struct {
	uint32_t Buttons;
	uint16_t LX;
	uint16_t LY;
	uint16_t RX;
	uint16_t RY;
	int16_t  AccelX;
	int16_t  AccelY;
	int16_t  AccelZ;
	int16_t  GyroX;
	int16_t  GyroY;
	int16_t  GyroZ;
} NS2ProDeviceState;

typedef struct {
	const char* SerialNumber;  // NULL = use default
	uint8_t     BatteryLevel;  // 0-9; 0 = use default (9 = full)
	uint8_t     Charging;      // 0 = not charging
	uint8_t     ExternalPower; // 0 = battery only
	uint16_t    BatteryVolts;  // mV; 0 = use default (3800)
} NS2ProMetaState;

typedef struct {
	uint8_t LeftRumble[16];
	uint8_t RightRumble[16];
	uint8_t Flags;
	uint8_t PlayerLedMask;
} NS2ProOutputState;

typedef void (*NS2ProOutputCallback)(NS2ProDeviceHandle handle, NS2ProOutputState output);

static void viiper_call_ns2pro_output(NS2ProOutputCallback fn, NS2ProDeviceHandle handle, NS2ProOutputState output) {
	fn(handle, output);
}


#line 1 "cgo-generated-wrapper"

#line 3 "server.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct {
	char* addr; // default "0.0.0.0:3241"
	uint64_t connection_timeout_ms; // default 30000 (30s)
	uint64_t device_handler_connect_timeout_ms; // default 5000 (5s)
	uint32_t write_batch_flush_interval_ms; // default 1 (1ms)
} USBServerConfig;

typedef uintptr_t USBServerHandle;

typedef enum {
    VIIPER_LOG_DEBUG = -4,
    VIIPER_LOG_INFO  = 0,
    VIIPER_LOG_WARN  = 4,
    VIIPER_LOG_ERROR = 8,
} VIIPERLogLevel;

typedef void (*VIIPERLogCallback)(VIIPERLogLevel level, const char* message);

static void viiper_call_log(VIIPERLogCallback fn, VIIPERLogLevel level, const char* msg) {
	fn(level, msg);
}

#line 1 "cgo-generated-wrapper"

#line 3 "steamcontroller.go"

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;
typedef uintptr_t SteamControllerDeviceHandle;

typedef enum {
    VIIPER_REMOVE_SUCCESS = 0,
    VIIPER_REMOVE_RETRYABLE_FAILURE = 1,
    VIIPER_REMOVE_UNSAFE_OUTCOME_UNKNOWN = 2,
    VIIPER_REMOVE_INVALID = 3
} SteamControllerDeviceRemoveResult;

typedef struct {
	uint8_t A, X, B, Y;
	uint8_t L1, R1;
	uint8_t L2, R2;
	uint8_t Menu, Steam, Options;
	uint8_t DPadDown, DPadLeft, DPadRight, DPadUp;
	uint8_t L3;
	uint8_t LGrip, RGrip;
	uint8_t LPadTouch, RPadTouch, LPadPress, RPadPress, LPadAndStick;
	int16_t LPadX, LPadY;
	int16_t RPadX, RPadY;
	uint16_t LTrigger, RTrigger;
	int16_t LStickX, LStickY;
	int16_t AccelX, AccelY, AccelZ;
	int16_t GyroX, GyroY, GyroZ;
	int16_t GyroQuatW, GyroQuatX, GyroQuatY, GyroQuatZ;
	uint16_t BatteryMilliVolts;
} SteamControllerDeviceState;

typedef void (*SteamControllerOutputCallback)(SteamControllerDeviceHandle handle, const uint8_t* data, uint32_t length);

static void viiper_call_steamcontroller_output(SteamControllerOutputCallback fn, SteamControllerDeviceHandle handle, const uint8_t* data, uint32_t length) {
	fn(handle, data, length);
}

#line 1 "cgo-generated-wrapper"

#line 3 "xbox360.go"

#include <stdint.h>
#include <stdlib.h>

typedef uintptr_t USBServerHandle;

typedef uintptr_t Xbox360DeviceHandle;

#define XBOX360_BUTTON_DPAD_UP     0x0001u
#define XBOX360_BUTTON_DPAD_DOWN   0x0002u
#define XBOX360_BUTTON_DPAD_LEFT   0x0004u
#define XBOX360_BUTTON_DPAD_RIGHT  0x0008u
#define XBOX360_BUTTON_START       0x0010u
#define XBOX360_BUTTON_BACK        0x0020u
#define XBOX360_BUTTON_LTHUMB      0x0040u
#define XBOX360_BUTTON_RTHUMB      0x0080u
#define XBOX360_BUTTON_LSHOULDER   0x0100u
#define XBOX360_BUTTON_RSHOULDER   0x0200u
#define XBOX360_BUTTON_GUIDE       0x0400u
#define XBOX360_BUTTON_A           0x1000u
#define XBOX360_BUTTON_B           0x2000u
#define XBOX360_BUTTON_X           0x4000u
#define XBOX360_BUTTON_Y           0x8000u

typedef struct {
	// Button bitfield (lower 16 bits used typically), higher bits reserved
	uint32_t Buttons;
	// Triggers: 0-255
	uint8_t LT;
	uint8_t RT;
	// Sticks: signed 16-bit little endian values
	int16_t LX;
	int16_t LY;
	int16_t RX;
	int16_t RY;
	uint8_t Reserved[6];
} Xbox360DeviceState;

typedef void (*Xbox360RumbleCallback)(Xbox360DeviceHandle handle, uint8_t leftMotor, uint8_t rightMotor);

static void viiper_call_rumble(Xbox360RumbleCallback fn, Xbox360DeviceHandle handle, uint8_t left, uint8_t right) {
	fn(handle, left, right);
}


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoUint8 CreateUSBBus(USBServerHandle handle, GoUint32* busID);
extern GoUint8 RemoveUSBBus(USBServerHandle handle, GoUint32 busID);
extern _Bool GetUSBDeviceIdentity(uintptr_t handle, uint32_t* outBusID, uint32_t* outDeviceID);
extern _Bool AttachUSBDevice(uintptr_t handle);
extern _Bool DetachUSBDevice(uintptr_t handle);
extern GoUint8 CreateDualSenseDevice(USBServerHandle serverHandle, DSDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct, DSMetaState* meta);
extern GoUint8 CreateDualSenseEdgeDevice(USBServerHandle serverHandle, DSDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct, DSMetaState* meta);
extern GoUint8 SetDualSenseDeviceState(DSDeviceHandle handle, DSDeviceState state);
extern GoUint8 SetDualSenseOutputCallback(DSDeviceHandle handle, DSOutputCallback cb);
extern GoUint8 RemoveDualSenseDevice(DSDeviceHandle handle);
extern GoUint8 CreateDS4Device(USBServerHandle serverHandle, DS4DeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct, DS4MetaState* meta);
extern GoUint8 SetDS4DeviceState(DS4DeviceHandle handle, DS4DeviceState state);
extern GoUint8 SetDS4OutputCallback(DS4DeviceHandle handle, DS4OutputCallback cb);
extern GoUint8 RemoveDS4Device(DS4DeviceHandle handle);
extern GoUint8 CreateKeyboardDevice(USBServerHandle serverHandle, KeyboardDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct);
extern GoUint8 SetKeyboardDeviceState(KeyboardDeviceHandle handle, KeyboardDeviceState state);
extern GoUint8 SetKeyboardLEDCallback(KeyboardDeviceHandle handle, KeyboardLEDCallback cb);
extern GoUint8 RemoveKeyboardDevice(KeyboardDeviceHandle handle);
extern GoUint8 CreateMouseDevice(USBServerHandle serverHandle, MouseDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct);
extern GoUint8 SetMouseDeviceState(MouseDeviceHandle handle, MouseDeviceState state);
extern GoUint8 RemoveMouseDevice(MouseDeviceHandle handle);
extern GoUint8 CreateNS2ProDevice(USBServerHandle serverHandle, NS2ProDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct, NS2ProMetaState* meta);
extern GoUint8 SetNS2ProDeviceState(NS2ProDeviceHandle handle, NS2ProDeviceState state);
extern GoUint8 SetNS2ProOutputCallback(NS2ProDeviceHandle handle, NS2ProOutputCallback cb);
extern GoUint8 RemoveNS2ProDevice(NS2ProDeviceHandle handle);
extern GoUint8 NewUSBServer(USBServerConfig* config, USBServerHandle* outHandle, VIIPERLogCallback logCallback);
extern GoUint8 CloseUSBServer(USBServerHandle handle);
extern GoUint8 CreateSteamControllerDevice(USBServerHandle serverHandle, SteamControllerDeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct);
extern GoUint8 SetSteamControllerDeviceState(SteamControllerDeviceHandle handle, SteamControllerDeviceState state);
extern GoUint8 SetSteamControllerOutputCallback(SteamControllerDeviceHandle handle, SteamControllerOutputCallback cb);
extern GoUint8 RemoveSteamControllerDevice(SteamControllerDeviceHandle handle);
extern SteamControllerDeviceRemoveResult RemoveSteamControllerDeviceEx(SteamControllerDeviceHandle handle);
extern GoUint8 CreateXbox360Device(USBServerHandle serverHandle, Xbox360DeviceHandle* outDeviceHandle, GoUint32 busID, GoUint8 autoAttachLocalhost, GoUint16 idVendor, GoUint16 idProduct, GoUint8 xinputSubType);
extern GoUint8 SetXbox360DeviceState(Xbox360DeviceHandle handle, Xbox360DeviceState state);
extern GoUint8 RemoveXbox360Device(Xbox360DeviceHandle handle);
extern GoUint8 SetXbox360RumbleCallback(Xbox360DeviceHandle handle, Xbox360RumbleCallback cb);

#ifdef __cplusplus
}
#endif
